### ISSUE TITLE
Define the variables that are in-scope when a property is expanded

### ISSUE THREAD

**Issue by xatapult** [Schematron/schematron-enhancement-proposals#13]
In the specification it is not defined what variables are in-scope when a property is expanded. So what variables is a `<value-of>` in a property allowed to reference?

I would expect only the variables that are lexically in scope, meaning, for properties, only global variables defined before the property is defined? Or also the variables that are defined in the pattern/rule that fired and caused the property to be expanded?

**Comment by rjelliffe** [comment]
Good question.

In general  the right answer should be the straightforward  thing that
gives the user the most value, I suggest.

In this case, it would clearly be that the property is evaluated in the
context of the assert etc. and so the variables should be visible.

The same would be true of diagnostics.

The reason that properties and diagnostics are declared outside the assert
statements is to keep asserts centred on the assertion text and not, by
allowing nested features, complicate their mark up and so dilute their
"essense", if that makes sense.

This is the same design rationale (which is really "separation of
concerns") why phases are siblings to patterns rather than containing them,
and why rules cannot contain rules or patterns cannot contain patterns. A
three-level structure (pattern/rule/assert) is already complex, but a
five-level structure  (phase/pattern/rule/assert/property) has too many
extraneous things to explain to someone just interested in the assert.


Regards
Rick Jelliffe

**Comment by dmj** [comment]
> In this case, it would clearly be that the property is evaluated in the
context of the assert etc. and so the variables should be visible.
>
> The same would be true of diagnostics.

I agree. Properties and diagnostics belong to the same "logical category", so to speak: They encode information relating to a failed assertion or successful report.

**Comment by AndrewSales** [comment]
Clarified this in latest draft for both properties and diagnostics.
