### ISSUE TITLE
Define whether parameters in abstract patterns are expanded in diagnostics and properties

### ISSUE THREAD

**Issue by dmj** [Schematron/schematron-enhancement-proposals#19]
See #10

**Comment by rjelliffe** [comment]
Yes, it is 100% a mistake if they do not. 

In fact, sch:property makes little sense without them, as you want computed values with information from the document. In particular, this is for "feature-extraction" usages more than classic "validation", perhaps.

Sch:diagnostic elements really need it, because the intent is to provide specific information to the user, to allow location and understanding of the problem. In fact, an over-thinker might say that assertions used properly should not allow sch:name and sch:value-of because their only use is for diagnostic text (e.g. error messages), but an sch:assert's text is a positive statement about the business requirement.

**Comment by AndrewSales** [comment]
Closing in light of #10 .
