### ISSUE TITLE
05.05.14 subject attribute [ref. JP31 032] 

### ISSUE THREAD

**Issue by AndrewSales** [Schematron/schematron-enhancement-proposals#55]
First, "may" is used in an inappropriate manner, since the validation result becomes unpredictable.
Second, is the subject node used for evaluating assertions?  Or, is it used for error message?
Third, "If no subject attribute is specified, the current subject node may be used" appears to be incorrect.  The current *context* node" should be used.

**Comment by rjelliffe** [comment]
The @subject  is not used for validation, merely for calculating the
location in the SVRL, e.g., so that the location better corresponds with
the text of the assertion.

But it can be cleared up.  The intent is

   1) If a rule has no @subject, the @context is its subject (provided in
its SVRL location)
   2) If an assertion has no @subject, the subject of its parent rule is
its subject (provided in its SVRL location)

The purpose is to decouple somewhat the implementation XPaths, the modeling
pragmatics of which assertions are grouped into which rules, the text of
the assertions, and the location information reported in the SVRL.

**Comment by AndrewSales** [comment]
Clarified in latest draft.
