### ISSUE TITLE
pattern/@documents: pattern variables in scope?

### ISSUE THREAD

**Issue by AndrewSales** [Schematron/schematron-enhancement-proposals#60]
With this pattern:

```
<pattern documents='/all/my/docs[@except = $these]'>
<let name='these' value='("avoid.xml", "avert.xml")'/>
[...]
```
I'm assuming (and [XQS](https://github.com/AndrewSales/XQS) does too) that `$these` is in scope when `@documents` is evaluated.

**Comment by xatapult** [comment]
IMHO, that does *not* make sense. Variables should be declared before being used.

**Comment by AndrewSales** [comment]
@xatapult that would be true _lexically_ speaking, but if the variable is to be scoped only to the pattern, there is no other option here.

**Comment by xatapult** [comment]
This would be a serious deviation of how variable scoping works in other X languages, for instance, XSLT. And therefore confusing.

In your example you simply would need to add the variable on the global level.

**Comment by rjelliffe** [comment]
Currently, the variable is interpreted in its current scope: for a pattern
this is its current document.

So it seems confusing that some variables in a pattern would be evaluated
first in the global scope, to get any values used in @document, but the
other variables in the pattern would be interpreted in the scope of the
pattern's current document.

A variable is not a macro. A macro is interpreted in the context of the
call (however it is located); but a variable is interpreted in the context
of its scope.

I think XQS is wrong, if it is accessing variables inside itself. But it
suggests a nice extension:

If it is desired to contain variables, there is a name for this already
used in Schematron: sch:param.

<sch:pattern document=" $xxx ">
   <sch:param name="xxx" value="'x.xml'" />

This would be powerful because it would then allow phase/active to be
parameterised, so that the same pattern could be invoked with different
parameters.

Rick

**Comment by AndrewSales** [comment]
> In your example you simply would need to add the variable on the global level.

Or in a `phase`, if applicable.

> But it suggests a nice extension:

I don't know @rjelliffe - possibly? I'm conscious that what I've raised here is quite an edge case with existing means to address it.
If you feel it deserves considering for the current revision of the standard, feel free to add an issue to this repo.

**Comment by AndrewSales** [comment]
Added a note about pattern variables being out of scope when evaluating `@documents` to draft of next edition.
