### ISSUE TITLE
Define whether a rule <extends href="..."> must be abstract

### ISSUE THREAD

**Issue by xatapult** [Schematron/schematron-enhancement-proposals#9]
The specification leaves open whether a rule included using a `<extends href="..."/>`  must be abstract or not. In both processors (ISO and Schxslt) it does not matter what you do on the included rule.

The specification *hints* that this included rule should *not* be abstract, but its says so with some detours. Let's make this clear.

BTW: I don't care whether or not it must be abstract or not. Maybe we can even leave the status quo (both situations are allowed). This is an enhancement proposal just to make it _clear_.

**Comment by dmj** [comment]
From my understanding it would be logical that a rule included with sch:extends/@href must be an abstract rule, too.

> The specification hints that this included rule should not be abstract, but its says so with some detours. Let's make this clear.

Could I ask you to explain which part of the specification you mean here?

**Comment by rjelliffe** [comment]
Actually, I cannot think of a  strict reason why it needs to be an abstract pattern. It might make cleaner rules.

*Perhaps* it is for clarity: you always know when changing an abstract rule that it effects its users, but you don't know when changing a rule that there may be other rules extending it: akin to the "fragile base class" problem in object-oriented programming.

Either way, it probably should be a rule in the same pattern, so that all pattern variables are  defined.  Or so that the code does not disappear due to naive implementation of phases stripping out unwanted phases.   The way things evolve, you would expect Schematron to have some "library" system.

**Comment by AndrewSales** [comment]
I assume @xatapult refers to the definition of element `rule` in Clause 5:

> An abstract rule is a list of assertions that will be invoked by other rules beloning to the same pattern using the `extends` element.

With the introduction of a library system and loosening the requirement for an extended rule to belong the same pattern, and also for backward compatibility with existing implementations, my feeling is we should make it explicit that they can be either abstract or not.

**Comment by AndrewSales** [comment]
> my feeling is we should make it explicit that they can be either abstract or not

I added a note to this effect to the definition of `extends`.
